[2025-05-14 14:07:34,632] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-14 14:07:43,435] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-14 14:07:43,446] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-14 14:07:43,450] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:19<00:59, 19.96s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:19<00:59, 19.96s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:19<00:59, 19.96s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:46<00:48, 24.10s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:46<00:48, 24.10s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:46<00:48, 24.10s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [01:14<00:25, 25.60s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [01:14<00:25, 25.60s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [01:14<00:25, 25.60s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:32<00:00, 22.68s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:32<00:00, 22.68s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:32<00:00, 22.68s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:32<00:00, 23.14s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [01:32<00:00, 23.14s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [01:32<00:00, 23.14s/it]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:22<00:22, 22.93s/it]Loading checkpoint shards:  50%|█████     | 1/2 [00:22<00:22, 22.91s/it]Loading checkpoint shards:  50%|█████     | 1/2 [00:22<00:22, 22.92s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:25<00:00, 10.77s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:25<00:00, 12.59s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:25<00:00, 10.77s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:25<00:00, 12.60s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:25<00:00, 10.79s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:25<00:00, 12.61s/it]
Traceback (most recent call last):
Traceback (most recent call last):
  File "/gscratch/stf/lbc800/mistral-KD/train_scripts/GKD.py", line 65, in <module>
  File "/gscratch/stf/lbc800/mistral-KD/train_scripts/GKD.py", line 65, in <module>
Traceback (most recent call last):
  File "/gscratch/stf/lbc800/mistral-KD/train_scripts/GKD.py", line 65, in <module>
    train_args = GKDConfig(
    TypeErrortrain_args = GKDConfig(: 
GKDConfig.__init__() got an unexpected keyword argument 'use_cache'    
train_args = GKDConfig(
TypeError: GKDConfig.__init__() got an unexpected keyword argument 'use_cache'
TypeError: GKDConfig.__init__() got an unexpected keyword argument 'use_cache'
W0514 14:10:00.643000 27619 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 27743 closing signal SIGTERM
E0514 14:10:00.660000 27619 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 1 (pid: 27744) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1196, in launch_command
    deepspeed_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 878, in deepspeed_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/gscratch/stf/lbc800/mistral-KD/train_scripts/GKD.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-05-14_14:10:00
  host      : g3110.hyak.local
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 27745)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-14_14:10:00
  host      : g3110.hyak.local
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 27744)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: g3110: task 0: Exited with exit code 1
