[2025-05-11 18:35:37,045] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-11 18:35:44,183] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-11 18:35:44,194] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-11 18:35:44,195] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:11<00:35, 11.75s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:11<00:35, 11.68s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:11<00:35, 11.69s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:27<00:28, 14.34s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:27<00:28, 14.34s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:28<00:28, 14.41s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:43<00:14, 14.86s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:43<00:14, 14.85s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:43<00:14, 14.85s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:54<00:00, 13.56s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:54<00:00, 13.73s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:54<00:00, 13.56s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:54<00:00, 13.73s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:55<00:00, 13.59s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:55<00:00, 13.77s/it]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:20<00:20, 20.30s/it]Loading checkpoint shards:  50%|█████     | 1/2 [00:20<00:20, 20.49s/it]Loading checkpoint shards:  50%|█████     | 1/2 [00:20<00:20, 20.45s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:21<00:00,  9.19s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:21<00:00, 10.88s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:21<00:00,  9.11s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:21<00:00, 10.79s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:21<00:00,  9.16s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:21<00:00, 10.85s/it]
Traceback (most recent call last):
  File "/gscratch/stf/lbc800/mistral-KD/train_scripts/GKD.py", line 53, in <module>
Traceback (most recent call last):
  File "/gscratch/stf/lbc800/mistral-KD/train_scripts/GKD.py", line 53, in <module>
    train_ds = train_ds.remove_columns("_messages")
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 557, in wrapper
    train_ds = train_ds.remove_columns("_messages")
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 557, in wrapper
Traceback (most recent call last):
  File "/gscratch/stf/lbc800/mistral-KD/train_scripts/GKD.py", line 53, in <module>
    train_ds = train_ds.remove_columns("_messages")
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 557, in wrapper
            out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)


  File "/usr/local/lib/python3.10/dist-packages/datasets/fingerprint.py", line 442, in wrapper
  File "/usr/local/lib/python3.10/dist-packages/datasets/fingerprint.py", line 442, in wrapper
  File "/usr/local/lib/python3.10/dist-packages/datasets/fingerprint.py", line 442, in wrapper
            out = func(dataset, *args, **kwargs)out = func(dataset, *args, **kwargs)out = func(dataset, *args, **kwargs)


  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 2161, in remove_columns
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 2161, in remove_columns
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 2161, in remove_columns
        raise ValueError(raise ValueError(

ValueError: Column name ['_messages'] not in the dataset. Current columns in the dataset: ['messages', 'input_ids', 'attention_mask', 'labels', 'prompt', 'prompt_input_ids', 'prompt_attention_mask']ValueError
: Column name ['_messages'] not in the dataset. Current columns in the dataset: ['messages', 'input_ids', 'attention_mask', 'labels', 'prompt', 'prompt_input_ids', 'prompt_attention_mask']
    raise ValueError(
ValueError: Column name ['_messages'] not in the dataset. Current columns in the dataset: ['messages', 'input_ids', 'attention_mask', 'labels', 'prompt', 'prompt_input_ids', 'prompt_attention_mask']
E0511 18:37:11.644000 40227 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 40430) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1196, in launch_command
    deepspeed_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 878, in deepspeed_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/gscratch/stf/lbc800/mistral-KD/train_scripts/GKD.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-05-11_18:37:11
  host      : g3102.hyak.local
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 40431)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-05-11_18:37:11
  host      : g3102.hyak.local
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 40432)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-11_18:37:11
  host      : g3102.hyak.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 40430)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: g3102: task 0: Exited with exit code 1
