[2025-05-14 01:00:08,417] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-14 01:00:15,412] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-14 01:00:15,415] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-14 01:00:15,434] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:11<00:33, 11.01s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:11<00:33, 11.00s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:11<00:33, 11.15s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:24<00:25, 12.59s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:24<00:25, 12.58s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:24<00:25, 12.60s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:39<00:13, 13.43s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:39<00:13, 13.48s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:39<00:13, 13.46s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:50<00:00, 12.51s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:50<00:00, 12.58s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:50<00:00, 12.51s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:50<00:00, 12.56s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:50<00:00, 12.53s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:50<00:00, 12.57s/it]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:19<00:19, 19.61s/it]Loading checkpoint shards:  50%|█████     | 1/2 [00:20<00:20, 20.14s/it]Loading checkpoint shards:  50%|█████     | 1/2 [00:20<00:20, 20.16s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:20<00:00,  8.84s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:20<00:00, 10.45s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:21<00:00,  9.03s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:21<00:00, 10.70s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:21<00:00,  9.04s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:21<00:00, 10.71s/it]
Traceback (most recent call last):
  File "/gscratch/stf/lbc800/mistral-KD/train_scripts/GKD.py", line 59, in <module>
Traceback (most recent call last):
  File "/gscratch/stf/lbc800/mistral-KD/train_scripts/GKD.py", line 59, in <module>
Traceback (most recent call last):
  File "/gscratch/stf/lbc800/mistral-KD/train_scripts/GKD.py", line 59, in <module>
        train_args = GKDConfig(train_args = GKDConfig(

TypeErrorTypeError: : GKDConfig.__init__() got an unexpected keyword argument 'truncation'GKDConfig.__init__() got an unexpected keyword argument 'truncation'

    train_args = GKDConfig(
TypeError: GKDConfig.__init__() got an unexpected keyword argument 'truncation'
E0514 01:01:37.456000 80581 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 80699) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1196, in launch_command
    deepspeed_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 878, in deepspeed_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/gscratch/stf/lbc800/mistral-KD/train_scripts/GKD.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-05-14_01:01:37
  host      : g3114.hyak.local
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 80700)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-05-14_01:01:37
  host      : g3114.hyak.local
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 80701)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-14_01:01:37
  host      : g3114.hyak.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 80699)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: g3114: task 0: Exited with exit code 1
