Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1189, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1017, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/config/config_args.py", line 72, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/config/config_args.py", line 156, in from_yaml_file
    raise ValueError(
ValueError: The config file at /gscratch/stf/lbc800/mistral-KD/default_config.yaml had unknown keys (['torchdynamo']), please try upgrading your `accelerate` version or fix (and potentially remove) these keys from your config file.
srun: error: g3110: task 0: Exited with exit code 1
